import Phaser from 'phaser';

export const defineConfig = () => ({
  // ゲーム設定
  GAME_WINDOW_WIDTH: 1024,
  GAME_WINDOW_HEIGHT: 800,
  GAME_FIELD_BUFFER: 80,
  WALLS_RESTITUTION: 1.0,
  WALLS_FRICTION: 0,
  GOAL_SPAWN_POINT: { x: 950, y: 760 },
  ENABLE_DEBUG_MODE: false,
  GAME_WINDOW_BG_COLOR: '#666666',

  // 敵の設定
  ENEMY_SPAWN_POINT: { x: 80, y: 80 },
  ENEMY_MAX_SPEED: 20,
  ENEMY_MIN_SPEED: 18,
  ENEMY_MAX_ANGULAR_VELOCITY: 10,
  ENEMY_RESTITUTION: 0,
  ENEMY_FRICTION: 0,
  ENEMY_FRICTION_AIR: 0.01,
  ENEMY_SLOP: 0,
  ENEMY_DENSITY: 0.0002,
  ENEMY_INITIAL_VELOCITY: { x: Phaser.Math.Between(-12, 12), y: Phaser.Math.Between(-12, 12) },
  ENEMY_INITIAL_ANGULAR_VELOCITY: 0.08,
  ENEMY_BOOST_SPEED_MULTIPLIER: 1.3,
  ENEMY_BOOST_ANGULAR_VELOCITY_MULTIPLIER: 1.12,

  // プレイヤーの設定
  PLAYER_MAX_SPEED: 8,
  PLAYER_SPAWN_POINT: { x: 30, y: 773 },
  PLAYER_RESTITUTION: 0,
  PLAYER_FRICTION: 0,
  PLAYER_FRICTION_AIR: 0.01,
  PLAYER_SLOP: 0,
  PLAYER_MOVE_FORCE_MAGNITUDE: 0.0035,
  PLAYER_STOP_FORCE_MULTIPLIER: 0.8,
  PLAYER_JUMP_FORCE: 12,
});
